### ISSUE TITLE
404 on save of setting page 

### ISSUE THREAD

**Issue by jlaughton87** [flipboxfactory/saml-sp#122]
Hi, im receiving the following error on save of the settings page (/saml-idp/settings):

![image](https://user-images.githubusercontent.com/14894660/125425797-eded506f-9e75-4f19-b06c-8848e04bd5ee.png)

```
yii\base\InvalidRouteException: Unable to resolve the request "saml-idp/settings/save". in /var/www/helpforce-sa-craft/current/pub/vendor/yiisoft/yii2/base/Module.php:543
Stack trace:
#0 /var/www/helpforce-sa-craft/current/pub/vendor/craftcms/cms/src/web/Application.php(278): yii\base\Module->runAction()
#1 /var/www/helpforce-sa-craft/current/pub/vendor/craftcms/cms/src/web/Application.php(581): craft\web\Application->runAction()
#2 /var/www/helpforce-sa-craft/current/pub/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest()
#3 /var/www/helpforce-sa-craft/current/pub/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#4 /var/www/helpforce-sa-craft/current/pub/index.php(22): yii\base\Application->run()
#5 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/helpforce-sa-craft/current/pub/vendor/craftcms/cms/src/web/Application.php:585
Stack trace:
#0 /var/www/helpforce-sa-craft/current/pub/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest()
#1 /var/www/helpforce-sa-craft/current/pub/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#2 /var/www/helpforce-sa-craft/current/pub/index.php(22): yii\base\Application->run()
#3 {main}
```

Any help would be great. 
Cheers

**Comment by dsmrt** [comment]
Is this for the saml-idp plugin (and not the sp)?

**Comment by jlaughton87** [comment]
You are correct, apologies, dont know where i linked to hear from.. I'll post on the correct plugin!

**Comment by dsmrt** [comment]
@jlaughton87 ok cool this helps. I'll take a look at the other issue. Thanks for transferring that over!
