### ISSUE TITLE
HTTP 400 Unable to verify your data submission

### ISSUE THREAD

**Issue by nickdunn** [flipboxfactory/saml-sp#140]
I'm setting up SAML SP against Azure AD, running Craft in an Azure App Service (Docker).

I've done this before for another site and it's working fine, but I'm bashing my head against the table this time.

* Plugin is configured following the excellent https://www.youtube.com/watch?v=Y1rau_dkdAU
* Azure AD configured
* `'requireResponseToBeSigned' => false` added to saml-sp.php per https://github.com/flipboxfactory/saml-sp/issues/128
* `loginPath` amended (`/paaas/sso/login/f216933b-1c03-47a6-815c-47d1eae99b55`)

(Note that my Craft instance is multi-site, one called `paaas` but all sites served as sub-paths on the same domain. Not sure if that makes a difference. I'm just using SAML for the Craft login, edits manage all sites in the instance.)

After authenticating Azure site I am redirected back to my loginPath (`/paaas/sso/login/f216933b-1c03-47a6-815c-47d1eae99b55`) but Craft returns a 400:

```
yii\web\BadRequestHttpException: Unable to verify your data submission. in /var/www/craft/vendor/yiisoft/yii2/web/Controller.php:218
Stack trace:
#0 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(138): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /var/www/craft/vendor/craftcms/cms/src/controllers/UsersController.php(137): craft\web\Controller->beforeAction(Object(yii\base\InlineAction))
#2 /var/www/craft/vendor/yiisoft/yii2/base/Controller.php(179): craft\controllers\UsersController->beforeAction(Object(yii\base\InlineAction))
#3 /var/www/craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('login', Array)
#4 /var/www/craft/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('login', Array)
#5 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(271): yii\base\Module->runAction('users/login', Array)
#6 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(584): craft\web\Application->runAction('users/login', Array)
#7 /var/www/craft/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /var/www/craft/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /var/www/craft/web/index.php(22): yii\base\Application->run()
#10 {main}
```

I can't see any other errors in the logs.

**Comment by nickdunn** [comment]
👋 

Should I remove this from `loginPath` **and** from the generated ACS and SLO URIs?

**Comment by nickdunn** [comment]
We changed all 3 but when I log in now AD gives me the error:

> AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'https://knowledge-app-service-dev.azurewebsites.net/'.

So I think this may be a bug with the plugin including the site prefix in the URLs?

**Comment by nickdunn** [comment]
![image](https://user-images.githubusercontent.com/39560/138058459-4e23650c-ead4-4d20-bc43-cac13a15d9cd.png)
