### ISSUE TITLE
Signature required but not found - After being returned from Azure AD.

### ISSUE THREAD

**Issue by syska** [flipboxfactory/saml-sp#147]
```
2021-11-26 03:30:20 [-][-][8ea22f3bb8fce640f56148398e25139d][warning][saml-core] Signature required but not found: Response
2021-11-26 03:30:20 [-][-][8ea22f3bb8fce640f56148398e25139d][error][Exception] Exception: Signature required but not found: Response in /vol/site/build.20211125-231814-21d3d2a8/vendor/flipboxfactory/saml-sp/src/validators/SignedElement.php:51
Stack trace:
#0 /vol/site/build.20211125-231814-21d3d2a8/vendor/flipboxfactory/saml-sp/src/validators/Response.php(86): flipbox\saml\sp\validators\SignedElement->validate(Object(SAML2\Response), Object(SAML2\Response\Validation\Result))
#1 /vol/site/build.20211125-231814-21d3d2a8/vendor/flipboxfactory/saml-sp/src/controllers/LoginController.php(111): flipbox\saml\sp\validators\Response->validate(Object(SAML2\Response))
#2 [internal function]: flipbox\saml\sp\controllers\LoginController->actionIndex('ba7676bc-0494-4...')
#3 /vol/site/build.20211125-231814-21d3d2a8/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /vol/site/build.20211125-231814-21d3d2a8/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#5 /vol/site/build.20211125-231814-21d3d2a8/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction('', Array)
#6 /vol/site/build.20211125-231814-21d3d2a8/vendor/craftcms/cms/src/web/Application.php(287): yii\base\Module->runAction('saml-sp/login', Array)
#7 /vol/site/build.20211125-231814-21d3d2a8/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('saml-sp/login', Array)
#8 /vol/site/build.20211125-231814-21d3d2a8/vendor/craftcms/cms/src/web/Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#9 /vol/site/build.20211125-231814-21d3d2a8/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /vol/site/build.20211125-231814-21d3d2a8/web/index.php(21): yii\base\Application->run()
#11 {main}
2021-11-26 03:30:20 [-][-][8ea22f3bb8fce640f56148398e25139d][info][application] $_GET = [
    'p' => 'sso/login/ba7676bc-0494-4fc1-a428-413c0464475e'
]
```

The XML after being returned from Azure AD looks like this. All sensitive information is removed. ( I hope )
```
<samlp:Response ID="_c4dfee62-8ed1-47b7-846e-aaface92d9e9" Version="2.0" IssueInstant="2021-11-26T02:05:07.635Z" Destination="https://www.foo.bar/sso/login/ba7676bc-0494-4fc1-a428-413c0464475e" InResponseTo="_b86b8e8cfad8ae835c258d0ce038c54320ff3dae62"
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
    <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://sts.windows.net/{removed}/</Issuer>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </samlp:Status>
    <Assertion ID="_5d789d3b-4e30-4214-920a-3850b024aa00" IssueInstant="2021-11-26T02:05:07.635Z" Version="2.0"
        xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
        <Issuer>https://sts.windows.net/{removed}/</Issuer>
        <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
            <SignedInfo>
                <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
                <Reference URI="#_5d789d3b-4e30-4214-920a-3850b024aa00">
                    <Transforms>
                        <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                    </Transforms>
                    <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                    <DigestValue>uyuaQwwSRHRbQFzPyUFIlsRmGZ8aJglojD5pZZ0ClzU=</DigestValue>
                </Reference>
            </SignedInfo>
            <SignatureValue>{Removed}</SignatureValue>
            <KeyInfo>
                <X509Data>
                    <X509Certificate>{Removed}</X509Certificate>
                </X509Data>
            </KeyInfo>
        </Signature>
        <Subject>
            <NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">Remove6@foo.bar</NameID>
            <SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <SubjectConfirmationData InResponseTo="_b86b8e8cfad8ae835c258d0ce038c54320ff3dae62" NotOnOrAfter="2021-11-26T03:05:07.510Z" Recipient="https://www.foo.bar/sso/login/ba7676bc-0494-4fc1-a428-413c0464475e"/>
            </SubjectConfirmation>
        </Subject>
        <Conditions NotBefore="2021-11-26T02:00:07.510Z" NotOnOrAfter="2021-11-26T03:05:07.510Z">
            <AudienceRestriction>
                <Audience>https://www.foo.bar/</Audience>
            </AudienceRestriction>
        </Conditions>
        <AttributeStatement>
            <Attribute Name="http://schemas.microsoft.com/identity/claims/tenantid">
                <AttributeValue>{removed}</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.microsoft.com/identity/claims/objectidentifier">
                <AttributeValue>Remove10</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.microsoft.com/identity/claims/displayname">
                <AttributeValue>Remove1</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.microsoft.com/identity/claims/identityprovider">
                <AttributeValue>https://sts.windows.net/{removed}/</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.microsoft.com/claims/authnmethodsreferences">
                <AttributeValue>http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/password</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname">
                <AttributeValue>Remove2</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname">
                <AttributeValue>Remove3</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
                <AttributeValue>Remove4@foo.bar</AttributeValue>
            </Attribute>
            <Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name">
                <AttributeValue>Remove4@foo.bar</AttributeValue>
            </Attribute>
        </AttributeStatement>
        <AuthnStatement AuthnInstant="2021-11-26T02:05:04.369Z" SessionIndex="_5d789d3b-4e30-4214-920a-3850b024aa00">
            <AuthnContext>
                <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef>
            </AuthnContext>
        </AuthnStatement>
    </Assertion>
</samlp:Response>
```

I have read this: https://github.com/flipboxfactory/saml-sp/issues/135

When setting these to false is works:
```
<?php

return [
   'requireResponseToBeSigned' => false,
   'requireAssertionToBeSigned' => false,
];
```

But this is ofcause not a good solution to the issue ... like ... it's not secure.

What am I doing wrong here? What is missing?

I have tried: https://www.samltool.com/validate_response.php

When pasting in the x509 cert that comes when adding the Azure AD as a IdP from the metadata ... it's validates.

So ... is there a bug? Can can I do to figure out what is actually wrong here ... i'm so lost.

Let me know if you need more information.

**Comment by dsmrt** [comment]
:wave: @syska,

Check this out: https://saml-sp.flipboxfactory.com/faqs.html#signature-required-but-not-found

It's a recent change to tighten up security. In your situation (since the assertion is being signed), you can get away with setting the `config/saml-sp.php`
with the following:

```php
return [
    // assertion is required but not the response
    'requireResponseToBeSigned' => false,
]; 
```

Let me know how this goes!

**Comment by syska** [comment]
@dsmrt 

WOW, 2 hours my post and already an answer. Now i'm the slow one. :-) 

So doing it this way is secure? SAML is just a complete mess in my head. Do you have a good link about the difference of these two things?

But I will give this a try.

**Comment by syska** [comment]
@dsmrt 

This works ... now I just need to understand what part of the XML Response is response. So if you have a link, with an explination. I seem to only find links that explains it exists, but now what they actual sign in the XML.

But ... i'm just happy both is not "false" anymore ...

**Comment by dsmrt** [comment]
Unfortunately time implementing and reading confusing documentation is the only way i’ve found to learn SAML. 

Unfortunately some of the best docs are some like this: https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-tech-overview-2.0.html

Response is the top level document/message you get back from the IdP (azure ad in your case). Assertions are within the response and contain the user attributes session info and more. 

There are some good blogs by auth0 and ping that explain SAML better than i can but let me know if you have specific questions.

**Comment by syska** [comment]
@dsmrt 

I think we will just leave it at `you got this` done right. :-) 

My head can't take anymore SAML ... just migrated from ADFS and i'm happy.
