### ISSUE TITLE
SSO Logout Request causes: Call to a member function getLocation() on null at /vendor/flipboxfactory/saml-core/src/services/messages/LogoutRequest.php:53

### ISSUE THREAD

**Issue by russclewett-mw** [flipboxfactory/saml-sp#191]
Hi there!

I've got the plugin set up for SSO with a Laravel based IDP.  SSO is working well when logging into Laravel and then redirecting to an sso login page on the craft site to initiate SSO and redirect back to Laravel.

However when we're initiating a Single Logout request (https://saml-sp.flipboxfactory.com/configure/logout.html) we're getting the following error:

[Error] Call to a member function getLocation() on null 
{
    "trace":
    [
        "#0 /home/***/***/vendor/flipboxfactory/saml-core/src/controllers/messages/AbstractLogoutController.php(195): flipbox\\saml\\core\\services\\messages\\LogoutRequest->create()",
        "#1 [internal function]: flipbox\\saml\\core\\controllers\\messages\\AbstractLogoutController->actionRequest()",
        "#2 /home/***/***/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()",
        "#3 /home/***/***/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams()",
        "#4 /home/***/***/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction()",
        "#5 /home/***/***/vendor/craftcms/cms/src/web/Application.php(302): yii\\base\\Module->runAction()",
        "#6 /home/***/***/vendor/yiisoft/yii2/web/Application.php(103): craft\\web\\Application->runAction()",
        "#7 /home/***/***/vendor/craftcms/cms/src/web/Application.php(287): yii\\web\\Application->handleRequest()",
        "#8 /home/***/***/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest()",
        "#9 /home/***/***/web/index.php(17): yii\\base\\Application->run()",
        "#10 {main}"
    ],
    "exception": "[object] (Error(code: 0): Call to a member function getLocation() on null at /home/***/***/vendor/flipboxfactory/saml-core/src/services/messages/LogoutRequest.php:53)"}

Login process is working fine but this error is occuring on logout.  Is there some additional configuration to be done with single logout?

Thanks

**Comment by dsmrt** [comment]
Looking at your IdP metadata (the Laravel instance metadata), is there a `SingleLogoutService` node in the xml? It might be missing which is causing this error.

Should look something like this:
```xml
<SingleLogoutService
            Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
            Location="https://LoadBalancer-9.siroe.com:3443/federation/
            SPSloRedirect/metaAlias/sp"
            ResponseLocation="https://LoadBalancer-9.siroe.com:3443/
            federation/SPSloRedirect/metaAlias/sp"/>
```

**Comment by dsmrt** [comment]
Closing this due to lack of activity. Let me know if you need anything else here.
